### ISSUE TITLE
It doesn't work now?

### ISSUE THREAD

**Issue by THCloud** [transcranial/atom-transparency#3]
Hi,
I wanna make atom transparent like yours, and I do the same configs like yours,
the only difference is I write the css into `style.less`
but it doesn't work after build.

Anything wrong with current version? 
Or do you have the version that works? Push it to a repo?

hoping for your reply, Tks !

**Comment by transcranial** [comment]
Yeah, it works for Atom versions up to 1.6. There are issues for 1.7+ which could be due to Electron. Currently investigating, any ideas welcome!
