### ISSUE TITLE
This does not work on 1.10.0-dev-672cf6d

### ISSUE THREAD

**Issue by victorhazbun** [transcranial/atom-transparency#4]
Screenshot: https://www.evernote.com/l/AWg-1cEtekNLjrHak_7pBcE10kg8bWt7tUY

**Comment by transcranial** [comment]
Yeah, it works for Atom versions up to 1.6. In 1.9+, the `src/browser/` folder was renamed to `src/main-process`, though this shouldn't be an issue as long as `atom-window.coffee` is still edited. There are issues for 1.7+ which I think could be due to Electron. Any ideas are welcome!
